### ISSUE TITLE
package.json entry point

### ISSUE THREAD

**Issue by SpiderSeb** [connorjs/css-typed#13]
Hello,

Could you add an entry point in your package.json please ?
("main" and/or "exports")

It will allow your package to be referenced in bundlephobia :)

**Comment by connorjs** [comment]
@SpiderSeb - What should `main` or `exports` point to given just `bin` right now?

I can point it to same JS file(s) if the idea is just to check download size for `npm install` (this should NOT end up in any final bundle).

**Comment by connorjs** [comment]
Example Bundlephobia run given OP’s request: <https://bundlephobia.com/package/css-typed@0.4.1>.

It has `node:*` issue, which looks to be same as <https://github.com/pastelsky/bundlephobia/issues/677>.

Calling this done.
